;; extends

;;; SU Constant
;;; top-level-namespace
((constant) @definition.constant.sketchup
  (#any-of? @definition.constant.sketchup
  "SB_PROMPT" "SB_VCB_LABEL" "SB_VCB_VALUE" "ORIGIN_2D" "ORIGIN" "X_AXIS_2D"
  "Y_AXIS_2D" "X_AXIS" "Y_AXIS" "Z_AXIS" "IDENTITY" "IDENTITY_2D" "MB_OK"
  "MB_OKCANCEL" "MB_ABORTRETRYIGNORE" "MB_YESNOCANCEL" "MB_YESNO"
  "MB_RETRYCANCEL" "MB_MULTILINE" "VK_SPACE" "VK_PRIOR" "VK_NEXT" "VK_END"
  "VK_HOME" "VK_LEFT" "VK_UP" "VK_RIGHT" "VK_DOWN" "VK_INSERT" "VK_DELETE"
  "MF_ENABLED" "MF_GRAYED" "MF_DISABLED" "MF_CHECKED" "MF_UNCHECKED" "VK_SHIFT"
  "VK_CONTROL" "VK_ALT" "VK_COMMAND" "VK_MENU" "ALT_MODIFIER_KEY"
  "ALT_MODIFIER_MASK" "COPY_MODIFIER_KEY" "COPY_MODIFIER_MASK"
  "CONSTRAIN_MODIFIER_KEY" "CONSTRAIN_MODIFIER_MASK" "IDOK" "IDCANCEL" "IDABORT"
  "IDRETRY" "IDIGNORE" "IDYES" "IDNO" "PAGE_USE_CAMERA"
  "PAGE_USE_RENDERING_OPTIONS" "PAGE_USE_SHADOWINFO" "PAGE_USE_SKETCHCS"
  "PAGE_USE_HIDDEN" "PAGE_USE_HIDDEN_GEOMETRY" "PAGE_USE_HIDDEN_OBJECTS"
  "PAGE_USE_LAYER_VISIBILITY" "PAGE_USE_SECTION_PLANES" "PAGE_USE_ALL"
  "PAGE_NO_CAMERA" "DimensionArrowNone" "DimensionArrowSlash"
  "DimensionArrowDot" "DimensionArrowClosed" "DimensionArrowOpen" "ALeaderNone"
  "ALeaderView" "ALeaderModel" "GL_POINTS" "GL_LINES" "GL_LINE_LOOP"
  "GL_LINE_STRIP" "GL_TRIANGLES" "GL_TRIANGLE_STRIP" "GL_TRIANGLE_FAN"
  "GL_QUADS" "GL_QUAD_STRIP" "GL_POLYGON" "LAYER_VISIBLE_BY_DEFAULT"
  "LAYER_HIDDEN_BY_DEFAULT" "LAYER_USES_DEFAULT_VISIBILITY_ON_NEW_PAGES"
  "LAYER_IS_VISIBLE_ON_NEW_PAGES" "LAYER_IS_HIDDEN_ON_NEW_PAGES" "CMD_SELECT"
  "CMD_PAINT" "CMD_ERASE" "CMD_RECTANGLE" "CMD_LINE" "CMD_CIRCLE" "CMD_ARC"
  "CMD_POLYGON" "CMD_FREEHAND" "CMD_PUSHPULL" "CMD_TEXT" "CMD_MOVE" "CMD_ROTATE"
  "CMD_EXTRUDE" "CMD_SCALE" "CMD_OFFSET" "CMD_MEASURE" "CMD_PROTRACTOR"
  "CMD_SKETCHCS" "CMD_SECTION" "CMD_DRAWOUTLINES" "CMD_DRAWCUTS" "CMD_ORBIT"
  "CMD_DOLLY" "CMD_ZOOM" "CMD_ZOOM_WINDOW" "CMD_ZOOM_EXTENTS" "CMD_CAMERA_UNDO"
  "CMD_WIREFRAME" "CMD_HIDDENLINE" "CMD_SHADED" "CMD_TEXTURED" "CMD_TRANSPARENT"
  "CMD_WALK" "CMD_PAN" "CMD_MAKE_COMPONENT" "CMD_DIMENSION" "CMD_VIEW_ISO"
  "CMD_VIEW_TOP" "CMD_VIEW_FRONT" "CMD_VIEW_RIGHT" "CMD_VIEW_BACK"
  "CMD_VIEW_LEFT" "CMD_VIEW_BOTTOM" "CMD_VIEW_PERSPECTIVE" "CMD_POSITION_CAMERA"
  "CMD_NEW" "CMD_OPEN" "CMD_SAVE" "CMD_CUT" "CMD_COPY" "CMD_PASTE" "CMD_DELETE"
  "CMD_UNDO" "CMD_REDO" "CMD_PRINT" "CMD_PAGE_NEW" "CMD_PAGE_DELETE"
  "CMD_PAGE_UPDATE" "CMD_PAGE_NEXT" "CMD_PAGE_PREVIOUS" "CMD_RUBY_CONSOLE"
  "CMD_SKETCHAXES" "CMD_SHOWHIDDEN" "CMD_SHOWHIDDENGEOMETRY"
  "CMD_SHOWHIDDENOBJECTS" "CMD_SHOWGUIDES" "CMD_SELECTION_ZOOM_EXT"
  "CMD_DISPLAY_FOV" "TB_HIDDEN" "TB_VISIBLE" "TB_NEVER_SHOWN" "TextAlignLeft"
  "TextAlignRight" "TextAlignCenter" "TextVerticalAlignBoundsTop"
  "TextVerticalAlignBaseline" "TextVerticalAlignCapHeight"
  "TextVerticalAlignCenter" "SKETCHUP_CONSOLE" "FILE_WRITE_OK"
  "FILE_WRITE_FAILED_INVALID_TYPE" "FILE_WRITE_FAILED_UNKNOWN"
  "SnapTo_Arbitrary" "SnapTo_Horizontal" "SnapTo_Vertical" "SnapTo_Sloped" ))

;;; constants
((constant) @definition.constant.sketchup
  (#any-of? @definition.constant.sketchup
  "NO_SMOOTH_OR_HIDE" "HIDE_BASED_ON_INDEX" "SOFTEN_BASED_ON_INDEX"
  "AUTO_SOFTEN" "SMOOTH_SOFT_EDGES" "MESH_POINTS" "MESH_UVQ_FRONT"
  "MESH_UVQ_BACK" "MESH_NORMALS" "LEADER_LINE_TYPE_SINGLE_SEGMENT"
  "LEADER_LINE_TYPE_TWO_SEGMENT" "LEADER_LINE_TYPE_BEZIER"
  "LEADER_LINE_TYPE_HIDDEN" "TYPE_FILE" "TYPE_PAGE_NAME" "TYPE_PAGE_NUMBER"
  "TYPE_CUSTOM_TEXT" "TYPE_DATE_CURRENT" "TYPE_DATE_CREATED"
  "TYPE_DATE_MODIFIED" "TYPE_DATE_PUBLISHED" "TYPE_MODEL_GROUP_NAME"
  "TYPE_MODEL_COMPONENT_INSTANCE_NAME" "TYPE_MODEL_COMPONENT_DEFINITION_NAME"
  "TYPE_MODEL_COMPONENT_DESCRIPTION" "TYPE_MODEL_VOLUME" "TYPE_MODEL_FACE_AREA"
  "TYPE_MODEL_EDGE_LENGTH" "TYPE_MODEL_COORDINATES"
  "TYPE_MODEL_DYNAMIC_COMPONENT_ATTRIBUTE" "TYPE_MODEL_CLASSIFIER_ATTRIBUTE"
  "TYPE_MODEL_COMPONENT_INSTANCE_ATTRIBUTE"
  "TYPE_MODEL_COMPONENT_DEFINITION_ATTRIBUTE" "TYPE_MODEL_SCENE_NAME"
  "TYPE_MODEL_SCENE_DESCRIPTION" "TYPE_MODEL_SCALE" "TYPE_MODEL_SECTION_NAME"
  "TYPE_MODEL_SECTION_SYMBOL" "TYPE_PAGE_COUNT" "TYPE_SEQUENCE"
  "TYPE_MODEL_RATIO" "NUMBER_STYLE_ARABIC" "NUMBER_STYLE_ARABIC_PADDED"
  "NUMBER_STYLE_UC_ALPHA" "NUMBER_STYLE_LC_ALPHA" "NUMBER_STYLE_UC_ROMAN"
  "NUMBER_STYLE_LC_ROMAN" "SEQUENCE_TYPE_PER_DOCUMENT" "SEQUENCE_TYPE_PER_PAGE"
  "VERSION_1" "VERSION_2" "VERSION_3" "VERSION_2013" "VERSION_2014"
  "VERSION_2015" "VERSION_2016" "VERSION_2017" "VERSION_2018" "VERSION_2019"
  "VERSION_2020" "VERSION_2021" "VERSION_2022" "VERSION_2023" "VERSION_CURRENT"
  "FRACTIONAL_INCHES" "DECIMAL_INCHES" "DECIMAL_FEET" "DECIMAL_MILLIMETERS"
  "DECIMAL_CENTIMETERS" "DECIMAL_METERS" "DECIMAL_POINTS" "GROW_MODE_UNBOUNDED"
  "GROW_MODE_BOUNDED" "ANCHOR_TYPE_TOP_LEFT" "ANCHOR_TYPE_CENTER_LEFT"
  "ANCHOR_TYPE_BOTTOM_LEFT" "ANCHOR_TYPE_TOP_RIGHT" "ANCHOR_TYPE_CENTER_RIGHT"
  "ANCHOR_TYPE_BOTTOM_RIGHT" "ANCHOR_TYPE_TOP_CENTER"
  "ANCHOR_TYPE_CENTER_CENTER" "ANCHOR_TYPE_BOTTOM_CENTER" "RESIZE_BEHAVIOR_NONE"
  "RESIZE_BEHAVIOR_BOUNDS" "RESIZE_BEHAVIOR_BOUNDS_AND_FONTS"
  "CONNECTION_TYPE_NONE" "CONNECTION_TYPE_AUTO" "CONNECTION_TYPE_REVERSE_AUTO"
  "CONNECTION_TYPE_TOP_LEFT" "CONNECTION_TYPE_CENTER_LEFT"
  "CONNECTION_TYPE_BOTTOM_LEFT" "CONNECTION_TYPE_TOP_RIGHT"
  "CONNECTION_TYPE_CENTER_RIGHT" "CONNECTION_TYPE_BOTTOM_RIGHT"
  "LEADER_LINE_TYPE_SINGLE_SEGMENT" "LEADER_LINE_TYPE_TWO_SEGMENT"
  "LEADER_LINE_TYPE_BEZIER" "LEADER_LINE_TYPE_UNKNOWN"
  "UNSHARELAYERACTION_CLEAR" "UNSHARELAYERACTION_COPYTOONEPAGE"
  "UNSHARELAYERACTION_COPYTOALLPAGES" "SHARELAYERACTION_CLEAR"
  "SHARELAYERACTION_KEEPONEPAGE" "SHARELAYERACTION_MERGEALLPAGES"
  "LEADER_LINE_TYPE_SINGLE_SEGMENT" "LEADER_LINE_TYPE_TWO_SEGMENT"
  "LEADER_LINE_TYPE_BEZIER" "LEADER_LINE_TYPE_HIDDEN" "RESOLUTION_LOW"
  "RESOLUTION_MEDIUM" "RESOLUTION_HIGH" "POINT_TYPE_MOVE_TO"
  "POINT_TYPE_LINE_TO" "POINT_TYPE_BEZIER_TO" "POINT_TYPE_ARC_CENTER"
  "POINT_TYPE_BEZIER_CONTROL" "POINT_TYPE_CLOSE" "PATH_WINDING_NONE"
  "PATH_WINDING_CLOCKWISE" "PATH_WINDING_COUNTER_CLOCKWISE" "TYPE_NORMAL"
  "TYPE_ROUNDED" "TYPE_LOZENGE" "TYPE_BULGED" "RASTER_RENDER" "HYBRID_RENDER"
  "VECTOR_RENDER" "CUSTOM_VIEW" "TOP_VIEW" "TOP_RELATIVE_VIEW" "BOTTOM_VIEW"
  "BOTTOM_RELATIVE_VIEW" "FRONT_VIEW" "BACK_VIEW" "LEFT_VIEW" "RIGHT_VIEW"
  "ISO_VIEW" "NO_OVERRIDE" "JOIN_STYLE_MITER" "JOIN_STYLE_ROUND"
  "JOIN_STYLE_BEVEL" "CAP_STYLE_FLAT" "CAP_STYLE_ROUND" "CAP_STYLE_SQUARE"
  "STROKE_PATTERN_SOLID" "STROKE_PATTERN_DASH" "STROKE_PATTERN_DOT"
  "STROKE_PATTERN_DASH_DOT" "STROKE_PATTERN_DASH_DOT_DOT"
  "STROKE_PATTERN_DASH_SPACE" "STROKE_PATTERN_DASH_DOT_DOT_DOT"
  "STROKE_PATTERN_DASH_DASH_DOT" "STROKE_PATTERN_DASH_DASH_DOT_DOT"
  "STROKE_PATTERN_DASH_DASH_DOT_DOT_DOT" "STROKE_PATTERN_CENTER"
  "STROKE_PATTERN_PHANTOM" "STROKE_PATTERN_SHORT_DASH" "UNDERLINE_NONE"
  "UNDERLINE_SINGLE" "UNDERLINE_DOUBLE" "NORMAL_SCRIPT"
  "SUPER_SCRIPT" "SUB_SCRIPT" "ALIGN_LEFT" "ALIGN_RIGHT" "ALIGN_CENTER"
  "ANCHOR_TOP" "ANCHOR_CENTER" "ANCHOR_BOTTOM" "DIMENSION_TEXT_ABOVE"
  "DIMENSION_TEXT_CENTER" "DIMENSION_TEXT_BELOW" "DIMENSION_TEXT_OFFSET"
  "DIMENSION_TEXT_HORIZONTAL" "DIMENSION_TEXT_VERTICAL"
  "DIMENSION_TEXT_PARALLEL" "DIMENSION_TEXT_PERPENDICULAR" "FRACTIONAL_INCHES"
  "ARCHITECTURAL_INCHES" "ENGINEERING_FEET" "DECIMAL_INCHES" "DECIMAL_FEET"
  "DECIMAL_MILLIMETERS" "DECIMAL_CENTIMETERS" "DECIMAL_METERS" "DECIMAL_POINTS"
  "DEGREES" "RADIANS" "ARROW_NONE" "ARROW_FILLED_TRIANGLE" "ARROW_OPEN_TRIANGLE"
  "ARROW_FILLED_SKINNY_TRIANGLE" "ARROW_OPEN_SKINNY_TRIANGLE"
  "ARROW_OPEN_ARROW_90" "ARROW_OPEN_ARROW_120" "ARROW_FILLED_CIRCLE"
  "ARROW_OPEN_CIRCLE" "ARROW_FILLED_SQUARE" "ARROW_OPEN_SQUARE"
  "ARROW_FILLED_DIAMOND" "ARROW_OPEN_DIAMOND" "ARROW_STAR" "ARROW_T"
  "ARROW_SLASH_RIGHT" "ARROW_SLASH_LEFT" "ARROW_UNDERRUN" "ARROW_OVERRUN"
  "LABEL_LEADER_LINE" "LABEL_TEXT" "DIMENSION_START_EXTENSION_LINE"
  "DIMENSION_END_EXTENSION_LINE" "DIMENSION_LINE" "DIMENSION_LEADER_LINE"
  "DIMENSION_TEXT" "ROTATION_0" "ROTATION_90" "ROTATION_180" "ROTATION_270"
  "Decimal" "Architectural" "Engineering" "Fractional" "Inches" "Feet"
  "Millimeter" "Centimeter" "Meter" "Yard" "SquareInches" "SquareFeet"
  "SquareMillimeter" "SquareCentimeter" "SquareMeter" "SquareYard" "CubicInches"
  "CubicFeet" "CubicMillimeter" "CubicCentimeter" "CubicMeter" "CubicYard"
  "Liter" "USGallon" "ARROW_NONE" "ARROW_SLASH" "ARROW_DOT" "ARROW_CLOSED"
  "ARROW_OPEN" "TEXT_OUTSIDE_START" "TEXT_CENTERED" "TEXT_OUTSIDE_END"
  "ALIGNED_TEXT_ABOVE" "ALIGNED_TEXT_CENTER" "ALIGNED_TEXT_OUTSIDE"
  "PointUnknown" "PointInside" "PointOnVertex" "PointOnEdge" "PointOnFace"
  "PointOutside" "PointNotOnPlane" "GET" "POST" "PUT" "DELETE" "HEAD" "OPTIONS"
  "PATCH" "STATUS_UNKNOWN" "STATUS_SUCCESS" "STATUS_PENDING" "STATUS_CANCELED"
  "STATUS_FAILED" "ImportSuccess" "ImportFail" "ImportCanceled"
  "ImportFileNotFound" "LICENSED" "EXPIRED" "TRIAL" "TRIAL_EXPIRED"
  "NOT_LICENSED" "MATERIAL_SOLID" "MATERIAL_TEXTURED"
  "MATERIAL_COLORIZED_TEXTURED" "COLORIZE_SHIFT" "COLORIZE_TINT" "OWNER_MANAGER"
  "OWNER_IMAGE" "OWNER_LAYER" "VERSION_3" "VERSION_4" "VERSION_5" "VERSION_6"
  "VERSION_7" "VERSION_8" "VERSION_2013" "VERSION_2014" "VERSION_2015"
  "VERSION_2016" "VERSION_2017" "VERSION_2018" "VERSION_2019" "VERSION_2020"
  "VERSION_2021" "ProTrial" "ProLicensed" "MakeTrial" "Make"
  "LOAD_STATUS_SUCCESS" "LOAD_STATUS_SUCCESS_MORE_RECENT" "ImageEmbedded"
  "ImageEmbeddedAndLinked" "ImageLinked" "UnitsPixels" "UnitsNormalizedX"
  "UnitsNormalizedY" "PICK_INSIDE" "PICK_CROSSING" "ROPAssign" "ROPDrawHidden"
  "ROPDrawHiddenGeometry" "ROPDrawHiddenObjects" "ROPEditComponent"
  "ROPSectionDisplayTurnedOff" "ROPSetBackgroundColor" "ROPSetConstructionColor"
  "ROPSetDepthQueEdges" "ROPSetDepthQueWidth" "ROPSetDisplayColorByLayer"
  "ROPSetDisplayDims" "ROPSetDisplayFog" "ROPSetDisplayInstanceAxes"
  "ROPSetDisplaySketchAxes" "ROPSetDisplayText" "ROPSetDisplayWatermarks"
  "ROPSetDrawBackEdges" "ROPSetDrawGround" "ROPSetDrawHorizon"
  "ROPSetDrawUnderground" "ROPSetEdgeColorMode" "ROPSetEdgeDisplayMode"
  "ROPSetEdgeType" "ROPSetExtendEdges" "ROPSetExtendLines" "ROPSetFaceColor"
  "ROPSetFogColor" "ROPSetFogDist" "ROPSetFogHint" "ROPSetFogUseBkColor"
  "ROPSetForegroundColor" "ROPSetGroundColor" "ROPSetGroundTransparency"
  "ROPSetHorizonColor" "ROPSetHideConstructionGeometry" "ROPSetHighlightColor"
  "ROPSetJitterEdges" "ROPSetLineEndEdges" "ROPSetLineEndWidth"
  "ROPSetLineExtension" "ROPSetLineStyleEdges" "ROPSetLockedColor"
  "ROPSetMaterialTransparency" "ROPSetModelTransparency"
  "ROPSetPhotomatchBackgroundOpacity" "ROPSetPhotomatchDrawBackground"
  "ROPSetPhotomatchDrawOverlay" "ROPSetPhotomatchOverlayOpacity"
  "ROPSetProfileEdges" "ROPSetProfilesOnlyEdges" "ROPSetProfileWidth"
  "ROPSetRenderMode" "ROPSetSectionActiveColor" "ROPSetSectionCutFilled"
  "ROPSetSectionCutWidth" "ROPSetSectionDefaultCutColor"
  "ROPSetSectionDefaultFillColor" "ROPSetSectionDisplayMode"
  "ROPSetSectionInactiveColor" "ROPSetSkyColor" "ROPSetTexture"
  "ROPSetTransparencyObsolete" "ROPSetXRayOpacity" "ROPTransparencySortMethod"
  "ROPSetFaceColorMode" "STYLE_WINDOW" "STYLE_DIALOG" "STYLE_UTILITY"
  "CEF_VERSION" "CHROME_VERSION" ))

;;; SU Modules
([
  (module name: (constant) @definition.namespace.sketchup)
  (call receiver: (constant) @definition.namespace.sketchup)
  (scope_resolution scope: (constant) @definition.namespace.sketchup)
  (scope_resolution name: (constant) @definition.namespace.sketchup)
  ] (#any-of? @definition.namespace.sketchup
  "Geom" "Http" "Layout" "Licensing" "RegionalSettings" "Sketchup" "Skp" "UI" ))

;;; SU Classes
([
  (class name: (constant)@definition.type.sketchup)
  (superclass (constant) @definition.type.sketchup)
  (call receiver: (constant) @definition.type.sketchup)
  (scope_resolution scope: (constant) @definition.type.sketchup)
  (scope_resolution name: (constant) @definition.type.sketchup)
  ] (#any-of? @definition.type.sketchup
  "AngularDimension" "Animation" "AppObserver" "Array" "ArcCurve"
  "AttributeDictionaries" "AttributeDictionary" "AutoTextDefinition"
  "AutoTextDefinitions" "Axes" "Behavior" "BoundingBox" "Bounds2d" "Camera"
  "ClassificationSchema" "Classifications" "Color" "Command"
  "ComponentDefinition" "ComponentInstance" "ConnectionPoint" "Console"
  "ConstructionLine" "ConstructionPoint" "Curve" "DefinitionList"
  "DefinitionObserver" "DefinitionsObserver" "Dimension" "DimensionLinear"
  "DimensionObserver" "DimensionRadial" "Document" "Drawingelement" "Edge"
  "EdgeUse" "Ellipse" "Entities" "EntitiesBuilder" "EntitiesObserver" "Entity"
  "EntityObserver" "ExtensionsManager" "Face" "FormattedText"
  "FrameChangeObserver" "Grid" "Group" "HtmlDialog" "Image" "ImageRep"
  "Importer" "InputPoint" "InstanceObserver" "InstancePath" "Label"
  "LanguageHandler" "LatLong" "Layer" "LayerFolder" "LayerInstance" "Layers"
  "LayersObserver" "Length" "LineStyle" "LineStyles" "LinearDimension"
  "LockedEntityError" "LockedLayerError" "Loop" "Material" "Materials"
  "MaterialsObserver" "Menu" "Model" "ModelObserver" "Notification" "Numeric"
  "OptionsManager" "OptionsProvider" "OptionsProviderObserver"
  "OrientedBounds2d" "Page" "PageInfo" "Pages" "PagesObserver" "Path"
  "PickHelper" "Point2d" "Point3d" "PolygonMesh" "Rectangle" "RenderingOptions"
  "RenderingOptionsObserver" "SectionPlane" "Selection" "SelectionObserver"
  "ShadowInfo" "ShadowInfoObserver" "SketchUpModel" "SketchupExtension" "String"
  "Style" "Styles" "Table" "TableCell" "TableColumn" "TableRow" "Text" "Texture"
  "TextureWriter" "Tool" "Toolbar" "Tools" "ToolsObserver" "Transformation"
  "Transformation2d" "UTM" "UVHelper" "Vector2d" "Vector3d" "Vertex" "View"
  "ViewObserver" "ReferenceEntity" "Overlay" "OverlaysManager" ))

;;; SU Operators
[
 "%"
 "*"
 "+"
 "-"
 "<"
 "<="
 "<=>"
 "=="
 ">"
 ">="
 "["
 "]"
 ] @definition.type.sketchup

;;; SU Methods
;;; method?
((call method: (identifier) @definition.method.sketchup)
 (#vim-match? @definition.method.sketchup
  "^(active|always_face_camera|arrow_type_filled|auto_scale|break_edges|camera_modified|casts_shadows|circular|clip_to_margins|closed|contains|convex|current_scene_modified|curve_interior|custom_text|cuts_opening|debug_mode|deleted|display|display_background|display_file_extension|display_full_path|display_leader|drawing_element_visible|effects_modified|empty|equals|file_loaded|fix_shadow_strings|fov_is_height|georeferenced|grid_snap_enabled|group|has_aligned_text|has_key|has_leader|hidden|identity|image|in_front|in_presentation|include|include_in_animation|inference_locked|internal|is2d|is_2d|is_64bit|is_curve|is_polygon|is_pro|is_surface|is_valid_filename|key|layer_visible|layers_modified|licensed|live_component|load_on_start|loaded|locked|mandatory|manifold|mipmapping|modified|navigation_buttons_enabled|no_scale_mask|object_snap_enabled|on_line|on_plane|on_shared_layer|outer|parallel|perpendicular|perspective|plugins_disabled|preserve_scale_on_resize|print|print_margins|print_paper_color|receives_shadows|registered|render_needed|reversed|reversed_in|same_direction|samedirection|shadows_face_sun|shared|show|show_major|show_margins|show_minor|single_object|smooth|soft|style_modified|supports_options|texture_positioned|texture_projected|toolbar_visible|unit_vector|unitvector|use_alpha|use_axes|use_camera|use_hidden|use_hidden_geometry|use_hidden_layers|use_hidden_objects|use_rendering_options|use_section_planes|use_shadow_info|use_style|used_by|valid|visible|visible_on_new_pages)[?]$"))

;;; method!
((call
  method: (identifier) @definition.method.sketchup)
 (#vim-match? @definition.method.sketchup "^(clear|copy|erase|invert|move|normalize|offset|reverse|set|transform)[!]$"))

;;; method=
(assignment left: (call
  method: (identifier) @definition.method.sketchup)
 (#vim-match? @definition.method.sketchup "^(always_face_camera|animation|auto_scale|break_edges|casts_shadows|clip_to_margins|cuts_opening|debug_mode|delay_time|display_background|display_file_extension|display_full_path|display_leader|drawing_color|dynamic|end_offset_length|extension|fill_color|fix_shadow_strings|folder|grid_snap_enabled|has_aligned_text|hidden|image_width|in_front|in_presentation|include_in_animation|is2d|line_stipple|line_width|locked|mipmapping|navigation_buttons_enabled|no_scale_mask|object_snap_enabled|perspective|plugins_disabled|preserve_scale_on_resize|print|print_margins|print_paper_color|receives_shadows|shadows_face_sun|show_major|show_margins|show_minor|smooth|soft|start_offset_length|status_text|suppress_dimension_units|symbol|tags|template|text|use_axes|use_camera|use_hidden|use_hidden_geometry|use_hidden_layers|use_hidden_objects|use_rendering_options|use_section_planes|use_shadow_info|use_style|vcb_label|vcb_value|visible|visible_on_new_pages|sequence_type|thumbnail_camera)$"))

((call
  method: (identifier) @definition.method.sketchup)
 (#any-of? @definition.method.sketchup
  "abort_operation" "activate" "active" "active_entities" "active_layer"
  "active_model" "active_path" "active_section_plane" "active_style"
  "active_style_changed" "active_tool" "active_tool_id" "active_tool_name"
  "active_view" "add" "add_3d_text" "add_action_callback" "add_arc" "add_circle"
  "add_classification" "add_cline" "add_context_menu_handler" "add_cpoint"
  "add_curve" "add_dimension_linear" "add_dimension_radial" "add_edge"
  "add_edges" "add_entity" "add_face" "add_faces_from_mesh" "add_folder"
  "add_frame_change_observer" "add_group" "add_image" "add_instance" "add_item"
  "add_layer" "add_line" "add_matchphoto_page" "add_ngon" "add_note"
  "add_observer" "add_point" "add_polygon" "add_section_plane" "add_separator"
  "add_style" "add_submenu" "add_text" "aligned_text_position" "all_connected"
  "all_picked" "allow_actions_from_host" "alpha" "angle" "angle_between"
  "app_name" "append_plain_text" "append_point" "apply_style" "arc"
  "arc_center_point" "arc_curve" "area" "arrow_type" "aspect_ratio" "at"
  "attached_to" "attribute_dictionaries" "attribute_dictionary"
  "auto_text_definitions" "average_color" "average_refresh_time" "axes"
  "back_material" "beep" "behavior" "best_picked" "bits_per_pixel" "blend"
  "blue" "body" "bottom_edge_style" "bottom_margin" "boundingbox_pick" "bounds"
  "bring_to_front" "build" "camera" "cancel" "center" "center_2d" "check"
  "circle" "classifications" "classify_point" "clear" "clear_texture_position"
  "clear_texture_projection" "clip_mask" "clone" "close" "close_active"
  "closest_points" "cm" "color" "color_at_uv" "colorize_deltas" "colorize_type"
  "colors" "commit_operation" "common_edge" "common_face" "connect"
  "connection_type" "copy" "copyright" "corner" "count" "count_edges"
  "count_folders" "count_instances" "count_layers" "count_points"
  "count_polygons" "count_used_instances" "create_cursor"
  "create_texture_writer" "creator" "cross" "current" "current_scene" "curve"
  "custom_text" "dash_scale" "data" "date_format" "days_remaining" "deactivate"
  "decimal_separator" "definition" "definitions" "degrees" "degrees_of_freedom"
  "delay_time" "delete" "delete_attribute" "delete_key" "depth" "depth_at"
  "description" "diagonal" "dimension_rotation_alignment" "dimension_units"
  "dimension_vertical_alignment" "dimensions" "direction" "disconnect"
  "display_name" "display_name_from_action" "display_resolution" "display_text"
  "distance" "distance_to_line" "distance_to_plane" "do_options" "do_pick"
  "document" "dot" "draw" "draw2d" "draw_line" "draw_lines" "draw_points"
  "draw_polyline" "draw_text" "drawing_bounds" "each" "each_edge" "each_folder"
  "each_key" "each_layer" "each_pair" "each_value" "edge" "edges" "edgeuses"
  "edit_transform" "element_at" "enable" "end" "end_angle" "end_arrow"
  "end_arrow_size" "end_arrow_type" "end_attached_to" "end_connection_point"
  "end_extent_point" "end_offset_point" "end_page" "end_point"
  "end_vertex_normal" "entities" "entity" "entity_index" "erase"
  "erase_entities" "error_description" "execute_script" "expects" "explode"
  "explode_curve" "export" "extension" "extension_path" "extensions" "eye"
  "face" "faces" "feet" "field_of_view" "file_extension" "file_loaded"
  "file_new" "filename" "fill_color" "fill_from_mesh" "find_entity_by_id"
  "find_entity_by_persistent_id" "find_faces" "find_support_file"
  "find_support_files" "first" "first_edge" "fit_plane_to_points" "focal_length"
  "focus" "folder" "folders" "followme" "font_family" "font_size" "format_angle"
  "format_area" "format_degrees" "format_length" "format_volume" "fov" "frame"
  "get" "get_UVHelper" "get_attribute" "get_back_UVQ" "get_classification_value"
  "get_column" "get_content_size" "get_datfile_info" "get_datum"
  "get_default_dialog_color" "get_drawingelement_visibility" "get_element_value"
  "get_extension_license" "get_front_UVQ" "get_glued_instances"
  "get_i18n_datfile_info" "get_last_state" "get_locale" "get_plane"
  "get_position" "get_product_family" "get_resource_path" "get_row"
  "get_shortcuts" "get_size" "get_sub_style" "get_texture_projection"
  "get_validation_proc" "glued_to" "green" "grid" "group" "grow_mode"
  "guess_target" "guid" "handle" "headers" "height" "hidden_entities" "hide"
  "icon_name" "icon_tooltip" "id" "image_display_resolution"
   "image_height" "image_output_resolution" "image_rep" "image_width"
  "import" "inch" "increment" "index" "init" "initial" "initialize" "inputbox"
  "inputpoint" "insert" "insert_column" "insert_row" "insertion_point" "inspect"
  "inspector_names" "install_from_archive" "instance_path"
  "instance_path_from_pid_path" "instances" "interpolate" "intersect"
  "intersect_line_line" "intersect_line_plane" "intersect_plane_plane"
  "intersect_with" "invalidate" "invalidate_bounds" "inverse" "invert"
  "is_online" "keys" "km" "label" "large_icon" "last_edge" "last_refresh_time"
  "latitude" "latlong_to_point" "layer" "layer_folders" "layer_instance"
  "layer_instances" "layers" "leader_break_point" "leader_line"
  "leader_line_type" "leader_points" "leader_type" "leaf" "leaf_at"
  "left_edge_style" "left_margin" "length" "line" "line_style" "line_styles"
  "line_weight" "linear_combination" "list_datums" "list_separator" "load"
  "load_file" "load_from_url" "load_schema" "load_texture" "local_bounds"
  "lock_inference" "longitude" "loop" "loops" "lower_left" "lower_right" "m"
  "major_color" "major_spacing" "make_unique" "margin_color" "material"
  "materials" "max" "max_height" "max_width" "menu" "menu_text" "merge" "mesh"
  "message" "messagebox" "method" "mile" "min" "min_height" "min_width"
  "minor_color" "minor_divisions" "mm" "model" "model_info_pages"
  "model_to_paper_point" "move_to_group" "move_to_layer" "move_vertices" "name"
  "names" "namespace" "new" "new_arc" "new_from_file" "next" "nitems"
  "nonshared_entities" "normal" "normal_at" "normalize" "number_faces"
  "number_style" "offset" "offset_vector" "on" "on_accept" "on_accept_title"
  "on_dismiss" "on_dismiss_title" "open" "open_file" "openpanel" "options"
  "origin" "os_language" "other_vertex" "outer_loop" "outer_shell"
  "output_entities" "output_resolution" "owner_type" "page" "page_behavior"
  "page_info" "page_number_style" "pages" "parametric_length" "parent"
  "parse_length" "partners" "path" "path_at" "pattern_fill_origin"
  "pattern_fill_path" "pattern_fill_rotation" "pattern_fill_scale"
  "pattern_filled" "pause" "persistent_id" "persistent_id_path" "pick"
  "pick_helper" "pick_segment" "picked_edge" "picked_element" "picked_face"
  "pickray" "pixelheight" "pixels_to_model" "pixelwidth" "place_component"
  "plain_text" "plane" "platform" "play_sound" "point" "point_at"
  "point_in_polygon_2" "point_index" "point_to_latlong" "point_to_utm"
  "point_types" "points" "polygon_at" "polygon_points_at" "polygons" "pop_tool"
  "position" "position_material"
  "post_url" "precision" "preferences_pages" "previous" "proc" "project_to_line"
  "project_to_plane" "purge_unused" "purge_unused_folders" "push_tool"
  "pushpull" "quit" "radians" "radius" "raytest" "read_default" "read_guid"
  "red" "redo" "refresh" "refresh_inspectors" "refresh_thumbnail"
  "refresh_toolbars" "register_extension" "register_importer" "release_texture"
  "remove" "remove_classification" "remove_column" "remove_entity"
  "remove_folder" "remove_frame_change_observer" "remove_layer"
  "remove_observer" "remove_row" "remove_scale_factor" "render" "render_mode"
  "render_mode_override" "rendering_options" "renumber" "reorder" "reorder_entity"
  "reset_camera" "reset_effects" "reset_layers" "reset_style" "resource_path"
  "restore" "resume" "reverse" "reverse_each" "right_edge_style" "right_margin"
  "root" "rotation" "row_padding" "rtf" "save" "save_as" "save_copy" "save_file"
  "save_thumbnail" "savepanel" "scale" "scale_2d" "scale_factor"
  "scale_precision" "scale_units" "scaling" "scenes" "screen_coords"
  "screen_scale_factor" "select_directory" "select_tool" "selected_page"
  "selected_style" "selection" "send_action" "send_to_layout" "sequence_format"
  "set" "set_attribute" "set_background_color" "set_can_close"
  "set_classification_value" "set_color_from_line" "set_content_size"
  "set_cursor" "set_data" "set_datum" "set_dimension_units"
  "set_download_progress_callback" "set_drawingelement_visibility" "set_file"
  "set_full_security" "set_html" "set_layer_visibility" "set_nonshared"
  "set_on_close" "set_on_closed" "set_plane" "set_point" "set_position"
  "set_scale_factor" "set_shared" "set_size" "set_status_text" "set_sub_style"
  "set_text" "set_texture_projection" "set_toolbar_visible"
  "set_upload_progress_callback" "set_url" "set_uv" "set_validation_proc"
  "set_visibility" "shadow_info" "shared_entities" "shift" "show"
  "show_differences" "show_extension_manager" "show_frame" "show_frame_at"
  "show_inspector" "show_modal" "show_model_info" "show_preferences"
  "show_ruby_panel" "size" "sketch_plane" "slideshow_time" "small_icon" "snapto"
  "solid_filled" "span" "split" "start" "start_angle" "start_arrow"
  "start_arrow_size" "start_arrow_type" "start_attached_to"
  "start_connection_point" "start_extent_point" "start_index"
  "start_offset_point" "start_operation" "start_page" "start_point"
  "start_timer" "start_vertex_normal" "state" "status" "status_bar_text"
  "status_code" "stipple" "stop" "stop_timer" "strings" "stroke_cap_style"
  "stroke_color" "stroke_join_style" "stroke_pattern" "stroke_pattern_scale"
  "stroke_width" "stroked" "style" "styles" "subtract"
  "suppress_dimension_units" "suspend" "symbol" "tag" "tags" "tangent_at"
  "target" "temp_dir" "template" "template_dir" "tesselate" "test_point" "text"
  "text_alignment" "text_anchor" "text_bold" "text_bounds" "text_color"
  "text_elevation" "text_italic" "text_position" "text_underline" "texture"
  "time_created" "time_modified" "time_published" "title" "to_a" "to_cm"
  "to_component" "to_f" "to_feet" "to_i" "to_inch" "to_km" "to_l" "to_latlong"
  "to_m" "to_mile" "to_mm" "to_s" "to_utm" "to_yard" "toggle" "toolbar"
  "toolbar_names" "tools" "tooltip" "top_edge_style" "top_margin" "transform"
  "transform_by_vectors" "transform_entities" "transformation"
  "transformation_at" "transition_time" "translation" "trim" "type" "typename"
  "uncheck" "undo" "ungroup" "union" "unique_name" "units" "unload_schema"
  "untransformed_bounds" "up" "update" "update_selected_style" "upper_left"
  "upper_right" "url" "utm_to_point" "uv_at" "uv_tile_at" "uvs" "values"
  "vector" "vector_to" "version" "version_id" "version_number" "vertex"
  "vertex_at" "vertices" "view" "volume" "vpheight" "vpwidth" "weld" "width"
  "winding" "window_pick" "write" "write_all" "write_default" "write_image"
  "write_thumbnail" "x" "xaxis" "y" "yard" "yaxis" "z" "zaxis" "zone_letter"
  "zone_number" "zoom" "zoom_extents" "zrotation" "resize_viewport" "overlays"
  "sequence_type" ))
